name: one_logger
description: Easy to use logger for single line logging. [date level service:module msg]
version: 1.0.12
repository: https://github.com/buraktabn/one_logger
issue_tracker: https://github.com/buraktabn/one_logger/issues

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  dio: ^5.1.2
  equatable: ^2.0.5
  intl: ^0.19.0
  tuple: ^2.0.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0
